CREATE TABLE t_64 (
    col1 NUMBER
);

DROP TABLE t_64;

INSERT INTO t_64 VALUES (NULL);
INSERT INTO t_64 VALUES (0);
INSERT INTO t_64 VALUES (NULL);
INSERT INTO t_64 VALUES (0);
INSERT INTO t_64 VALUES (NULL);

SELECT * FROM t_64;

SELECT CASE A.col1 WHEN null then -1 else 0 as C1 from A;