-- 계층형 조회 (CONNECT BY)
CREATE TABLE TAB1(
    C1 VARCHAR2(1),
    C2 VARCHAR2(1),
    C3 VARCHAR2(1)
);

INSERT INTO TAB1 VALUES ('1', NULL, 'A');
INSERT INTO TAB1 VALUES ('2', 1, 'B');
INSERT INTO TAB1 VALUES ('3', 1, 'C');
INSERT INTO TAB1 VALUES ('4', 2, 'D');

SELECT * FROM TAB1;

CREATE TABLE FAMILY (
    FAMILY_ID   NUMBER,
    FAMILY_NAME VARCHAR(15),
    PARENT_ID   NUMBER
);

INSERT INTO FAMILY VALUES (1, '할머니', NULL);
INSERT INTO FAMILY VALUES (2, '아빠', 3);
INSERT INTO FAMILY VALUES (3, '할아버지', NULL);
INSERT INTO FAMILY VALUES (4, '엄마', 1);
INSERT INTO FAMILY VALUES (5, '딸', 4);
INSERT INTO FAMILY VALUES (6, '아들', 2);


COMMIT;

SELECT * FROM FAMILY;
--상위 계층인 PARENT / NULL 찾기 쉬움

--  PARENT_ID 상위컬럼 부모 / FAMILY_ID 하위컬럼 자식

SELECT * FROM FAMILY
-- PARENT_ID 4에서 시작
    START WITH PARENT_ID = 4
-- 이전 PARENT_ID와 FAMILY_ID가 같은 (조인조건)
    CONNECT BY FAMILY_ID = PRIOR PARENT_ID;
    
/*
5 딸 4
4 엄마 1
1 할머니 NULL
*/








