-- 뷰 만들기 view 
CREATE TABLE JOB_INFO(
    JOB_ID   VARCHAR(10),
    MIN_SALARY NUMBER,
    MAX_SALARY NUMBER
);

INSERT INTO JOB_INFO VALUES ('AD_PRES', 20080, 40000);
INSERT INTO JOB_INFO VALUES ('AD_VP', 15000, 30000);
INSERT INTO JOB_INFO VALUES ('AD_ASST', 3000, 6000);
INSERT INTO JOB_INFO VALUES ('FI_MGR', 8200, 16000);
INSERT INTO JOB_INFO VALUES ('FI_ACCOUNT', 4200, 9000);
INSERT INTO JOB_INFO VALUES ('AC_MGR', 8200, 16000);
INSERT INTO JOB_INFO VALUES ('FI_ACCOUNT', 4200, 9000);

SELECT * FROM JOB_INFO;


SELECT * FROM JOB_INFO
WHERE MIN_SALARY > 5000;

-- V_JOB_INFO 뷰 만들기
CREATE VIEW V_JOB_INFO AS
SELECT * FROM JOB_INFO
WHERE MIN_SALARY > 5000;

SELECT * FROM v_job_info;

-- 최대급여에서 최저급여 차이가 8000이상인 직업 아이디 수
SELECT COUNT(*)
FROM V_JOB_INFO
WHERE MAX_SALARY - MIN_SALARY > 8000;









